apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "incident-api.fullname" . }}-config

data:
    PORT: "8080"
    DB_HOST: "incident-db.chyiggu0sym2.eu-west-1.rds.amazonaws.com"
    DB_PORT: "5432"
    DB_NAME: "incident_tracker"
    DB_USER: "postgres"